image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/cibase:0.5.0

stages:
  - unit-test
  - docker-build
  - web-hook

maven-test-branches:
  stage: unit-test
  script:
    - mvn package -U -DskipTests=false
    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID || true
  only:
    - branches
  except:
    - master
    - tags
    - develop
    - /^release-.*$/
    - /^hotfix-.*$/

maven-test-docker:
  stage: unit-test
  script:
    - update_pom_version
    - mvn package -U -DskipTests=false
    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.analysis.serviceGroup=$SERVICE_GROUP -Dsonar.analysis.commitId=$CI_COMMIT_SHA || true
    - mkdir -p $HOME/.m2/$CI_COMMIT_SHA
    - cp target/app.jar $HOME/.m2/$CI_COMMIT_SHA/hap-eureka-server.jar
  only:
    - tags
    - develop
    - /^release-.*$/
    - /^hotfix-.*$/

docker-build:
  stage: docker-build
  script:
    - cp $HOME/.m2/$CI_COMMIT_SHA/hap-eureka-server.jar src/main/docker/app.jar
    - docker login -u $REGISTRY_USER -p $REGISTRY_PWD $REGISTRY_ADDRESS
    - docker build --pull -t $REGISTRY_ADDRESS/$PROJECT_NAME/$APPLICATION_NAME:$CI_COMMIT_TAG src/main/docker
    - docker push $REGISTRY_ADDRESS/$PROJECT_NAME/$APPLICATION_NAME:$CI_COMMIT_TAG
    - rm -rf $HOME/.m2/$CI_COMMIT_SHA
  only:
    - tags
    - develop
    - /^release-.*$/
    - /^hotfix-.*$/

notification:
  stage: web-hook
  script:
    - devops_ci_notification
  only:
    - tags
    - develop
    - /^release-.*$/
    - /^hotfix-.*$/

.auto_devops: &auto_devops |
  export CI_TAG_SUF=$(echo $CI_COMMIT_REF_NAME | awk -F '-' '{print $1}')
  export CI_TAG_PRE=$(echo $CI_COMMIT_REF_NAME | awk -F '-' '{print $2}')
  export CI_COMMIT_TIME=$(git log -1 --pretty=format:"%ci" | awk '{print $1$2}' | sed 's/[-:]//g')
  if [ ! $CI_TAG_PRE ]; then
    export CI_APPLICATION_TAG=$CI_TAG_SUF.$CI_COMMIT_TIME
  else
    export CI_APPLICATION_TAG=$CI_TAG_PRE-beta.$CI_COMMIT_TIME.$CI_TAG_SUF
  fi
  if [ ! $CI_COMMIT_TAG ]; then
    export CI_COMMIT_TAG=$CI_APPLICATION_TAG
  fi

  function update_pom_version(){
    find . -name pom.xml | xargs xml ed \
        -L -N x=http://maven.apache.org/POM/4.0.0 -u '/x:project/x:version' -v "${CI_COMMIT_TAG}"
    find . -name pom.xml | grep -v "\./pom.xml" | xargs xml ed \
        -L -N x=http://maven.apache.org/POM/4.0.0 -u '/x:project/x:parent/x:version' -v "${CI_COMMIT_TAG}" 2>/dev/null || true
  }

before_script:
  - *auto_devops